module: SwiftyJIRA
author: Joe DeCapo
author_url: polka.cat
github_url: https://github.com/polka-dot-cat/SwiftyJIRA
exclude: ["script"]
xcodebuild_arguments: [-scheme,SwiftyJIRA-Package]
swift_version: 4.0
output: docs/jazzy
