matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
    - os: osx
      osx_image: xcode9.1
      language: objective-c
      sudo: required

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - sudo pip install codecov
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo gem install jazzy; fi

before_script: script/update

script:
  - swift build
  - swift test

after_success:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then jazzy; fi
  - bash <(curl -s https://codecov.io/bash)

branches:
  only: # whitelist
    - master

notifications:
  email: false
