matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
    - os: osx
      osx_image: xcode9.1
      language: objective-c
      sudo: required

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo gem install jazzy; fi

before_script: script/update

script: swift build

after_success: if [ "$TRAVIS_OS_NAME" = "osx" ]; then jazzy; fi

branches:
  only: # whitelist
    - master

notifications:
  email: false
